# Generated by Django 2.1.1 on 2018-09-25 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(default=0, verbose_name='学科id')),
                ('title', models.CharField(max_length=80, verbose_name='阶段标题')),
                ('number', models.IntegerField(default=0, verbose_name='排序')),
                ('days', models.IntegerField(default=0, verbose_name='学时')),
                ('project', models.CharField(max_length=255, verbose_name='项目')),
                ('teaching', models.CharField(max_length=255, verbose_name='教学方法')),
                ('learning', models.CharField(max_length=255, verbose_name='学习方法')),
                ('sharing', models.CharField(max_length=255, verbose_name='学生分享')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('ceater', models.IntegerField(default=datetime.datetime(2018, 9, 25, 14, 56, 2, 818582), verbose_name='创建时间')),
                ('updater', models.IntegerField(default=0, verbose_name='更新者')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 9, 25, 14, 56, 2, 818582), verbose_name='更新时间')),
            ],
            options={
                'db_table': 'stage',
            },
        ),
    ]
