# Generated by Django 2.1.1 on 2018-09-26 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemodel',
            name='ceater',
            field=models.CharField(max_length=255, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='status',
            field=models.CharField(max_length=255, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='subject_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Java')], default=0, verbose_name='学科id'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 14, 24, 24, 834664), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='updater',
            field=models.CharField(max_length=255, verbose_name='更新者'),
        ),
    ]
