# Generated by Django 2.1.1 on 2018-09-25 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(null=True)),
                ('days', models.IntegerField()),
                ('amount', models.CharField(max_length=100)),
                ('assurance', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('stauts', models.CharField(max_length=100, null=True)),
                ('creater', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 9, 25, 14, 55, 43, 896500))),
                ('updater', models.CharField(max_length=100, null=True)),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 9, 25, 14, 55, 43, 896500))),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
