# Generated by Django 2.1.1 on 2018-09-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(choices=[(1, 'Python'), (2, 'Java')], default=0, verbose_name='学科id')),
                ('stage_id', models.IntegerField(choices=[(5, '第一阶段'), (8, '第二阶段'), (9, '第五阶段'), (12, '第二阶段'), (13, '第三阶段')], default=0, verbose_name='阶段id')),
                ('outline_id', models.IntegerField(choices=[(1, '大纲一'), (2, '大纲二'), (4, '大纲三')], default=0, verbose_name='大纲id')),
                ('number', models.IntegerField(default=0, verbose_name='天序')),
                ('sign', models.CharField(max_length=80, verbose_name='标志性内容')),
                ('digest', models.CharField(max_length=255, verbose_name='内容摘要')),
                ('prepare', models.CharField(max_length=255, verbose_name='准备工作')),
                ('process', models.CharField(max_length=255, verbose_name='讲课流程')),
                ('attention', models.CharField(max_length=255, verbose_name='注意事项')),
                ('exercise', models.CharField(max_length=255, verbose_name='课后作业')),
                ('share', models.CharField(max_length=255, verbose_name='学生分享')),
                ('management', models.CharField(max_length=255, verbose_name='管理事项')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'db_table': 'program',
            },
        ),
    ]
